# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171105_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
