# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(to='contacts.Tag'),
        ),
    ]
