# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20180305_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
