# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, choices=[('CL', 'Cell'), ('HM', 'Home'), ('WO', 'Work'), ('OT', 'Other')], max_length=2),
        ),
    ]
