# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_phone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
